using Gluten.Core.DataProcessing.Service;
using Gluten.Core.LocationProcessing.Service;
using Gluten.Data.ClientModel;
using Gluten.Data.MapsModel;
using Gluten.Data.TopicModel;
using Gluten.Data.Access.Service;
using Gluten.Data.Access.DatabaseModel;
using Gluten.Core.Helper;
using Gluten.Core.Interface;


namespace Frodo.Service
{
    /// <summary>
    /// Generates and exports data to the client database
    /// </summary>
    internal class ClientExportFileGeneratorGM(DatabaseLoaderService _databaseLoaderService,
        GeoService _geoService,
        CloudDataStore _dataStore,
        IConsole Console
        )
    {
        /// <summary>
        /// Group data by pin (venue), export to json
        /// </summary>
        public void GenerateTopicExport(List<DetailedTopic> topics, List<PinTopic> pins, string exportFolder)
        {
            var gmPins = _databaseLoaderService.LoadGMPins();

            GenerateGMPinExport(pins);
            var gmPinsWithDescriptions = gmPins.Where(x => !string.IsNullOrWhiteSpace(x.Comment) && x.Comment.Contains("gluten", StringComparison.InvariantCultureIgnoreCase)).ToList();
            WriteToDatabase(gmPinsWithDescriptions);
            CreateExportFolderDataGM(gmPins, exportFolder);
        }

        private void GenerateGMPinExport(List<PinTopic> pins)
        {
            var gmPins = _databaseLoaderService.LoadGMPins();
            var sharedGMPins = _databaseLoaderService.LoadGMSharedPins();

            List<GMapsPin> exportPins = [];

            foreach (var pin in gmPins)
            {
                if (pin.MapsLink == null)
                {
                    pin.MapsLink = pin.MapsUrl;
                }
                if (!string.IsNullOrWhiteSpace(pin.Comment)
                    && pin.GeoLatitude != null
                    && pin.GeoLongitude != null
                    && !PinHelper.IsInList(pins, double.Parse(pin.GeoLatitude), double.Parse(pin.GeoLongitude)))
                {
                    pin.Description = $"Pin generated from Google maps - {pin.Comment}";
                    exportPins.Add(pin);
                }
            }

            // Add pins that have been shared through GM lists
            int sharedPinCount = 0;
            foreach (var pin in sharedGMPins)
            {
                if (pin.MapsLink == null)
                {
                    pin.MapsLink = pin.MapsUrl;
                }

                if (!string.IsNullOrWhiteSpace(pin.Comment)
                    && pin.GeoLatitude != null
                    && pin.GeoLongitude != null
                    && !PinHelper.IsInList(pins, double.Parse(pin.GeoLatitude), double.Parse(pin.GeoLongitude)))
                {
                    pin.Description = $"Pin from shared list - {pin.Comment}";
                    exportPins.Add(pin);
                    sharedPinCount++;
                }
            }

            //_databaseLoaderService.SaveGMPins(gmPins);
            //_databaseLoaderService.SaveGMSharedPins(sharedGMPins);


            _databaseLoaderService.SaveGMMapPinExport(exportPins);

            Console.WriteLine($"Exported {sharedPinCount} shared pins");
            Console.WriteLine($"Exported {exportPins.Count} pins generated by google maps ");
        }

        private static void SaveDb<typeToSave>(string fileName, typeToSave topics)
        {
            JsonHelper.SaveDbNoPadding(fileName, topics);
        }

        private GMapsPinDb? FindDbPin(List<GMapsPinDb> dbPins, GMapsPin gMapsPin)
        {
            foreach (var pin in dbPins)
            {
                if (pin.GeoLatitude == gMapsPin.GeoLatitude && pin.GeoLongitude == gMapsPin.GeoLongitude)
                {
                    return pin;
                }
            }
            return null;
        }

        private void WriteToDatabase(List<GMapsPin> gmPins)
        {
            var mapper = new DbMapper();

            // delete locally removed
            var itemsGm = _dataStore.GetData<GMapsPinDb>("").Result;
            for (int i = 0; i < itemsGm.Count; i++)
            {
                var item = itemsGm[i];
                if (!gmPins.Exists(o => o.GeoLatitude == item.GeoLatitude && o.GeoLongitude == item.GeoLongitude))
                {
                    Console.WriteLine($"Delete GMPin {i}");
                    _dataStore.DeleteItemAsync(item).Wait();
                }
            }

            for (int i = 0; i < gmPins.Count; i++)
            {
                var item = gmPins[i];
                var existingDbPin = FindDbPin(itemsGm, item);
                item.Description = $"Pin generated from Google maps - {item.Comment}";

                if (existingDbPin == null
                    || existingDbPin.Label != item.Label
                    || existingDbPin.MapsUrl != item.MapsUrl
                    || existingDbPin.MapsLink != item.MapsLink
                    || existingDbPin.RestaurantType != item.RestaurantType
                    || existingDbPin.Price != item.Price
                    || existingDbPin.Stars != item.Stars
                    || existingDbPin.Comment != item.Comment
                    || existingDbPin.Description != item.Description)
                {
                    Console.WriteLine($"Writing GM to database {i}");
                    var dbItem = mapper.Map<GMapsPinDb, GMapsPin>(item);
                    dbItem.Country = _geoService.GetCountryPin(item);
                    _dataStore.ReplaceItemAsync(dbItem).Wait();
                }
            }
        }

        private void CreateExportFolderDataGM(List<GMapsPin> pins, string exportFolder)
        {
            Dictionary<string, List<GMapsPin>> files = [];

            foreach (var item in pins)
            {
                var pinCountry = _geoService.GetCountryPin(item);

                if (!string.IsNullOrWhiteSpace(pinCountry))
                {
                    if (!files.TryGetValue(pinCountry, out List<GMapsPin>? value))
                    {
                        value = ([]);
                        files.Add(pinCountry, value);
                    }

                    value.Add(item);
                }
            }

            foreach (var file in files)
            {
                SaveDb(exportFolder + file.Key + "GM.json", file.Value);
            }
        }




    }
}
