using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gluten.Core.LocationProcessing.Service
{
    public class RestaurantTypeService
    {
        private readonly List<string> _restaurantTypes = [];

        private readonly List<string> _rejectionList = [
            "Adult education school",
            "Aged Care Service",
            "Agricultural service",
            "Airline",
            "Animal hospital",
            "Arts organization",
            "Auditor",
            "Auto body parts supplier",
            "Bail bonds service",
            "Baseball field",
            "Beauty product supplier",
            "Beauty salon",
            "Biotechnology company",
            "Boat tour agency",
            //"Buddhist temple",
            "Bridge",
            "Business center",
            "Car dealer",
            "Cars",
            "Car racing track",
            "Charity",
            "Children's book store",
            "Clothes market",
            "Company",
            "Condominium complex",
            "Conference center",
            "Corporate office",
            "Cooking school",
            "Criminal justice attorney",
            "Cruise line company",
            //"Dairy farm",
            "Diagnostic center",
            "Driveshaft shop",
            "Dry cleaner",
            "E-commerce service",
            "Education center",
            "Electronics manufacturer",
            "Embassy",
            "Energy equipment and solutions",
            "Executive search firm",
            "Exhibit",
            "Exporter",
            "Fashion designer",
            "Florist",
            "Fitness center",
            "Freight forwarding service",
            "Food manufacturer",
            "Furniture accessories",
            "Furniture maker",
            "Garden",
            "Glazier",
            "Golf course",
            //"Grain elevator",
            "Graphic designer",
            "Gym",
            "Hairdresser",
            "Handyman/Handywoman/Handyperson",
            "Health consultant",
            "Heritage building",
            "Hindu temple",
            //"Holiday home",
            //"Homestay",
            "Hair salon",
            "Historical landmark",
            "House cleaning service",
            "Housing complex",
            "Island",
            "Karaoke Equipment Hire Service",
            "Laundromat",
            "Landmark",
            "Language school",
            "Lawn bowls club",
            "Lawn care service",
            "Manufacturer",
            "Marriage or relationship counselor",
            "Masonic Centre",
            "Massage therapist",
            "Media house",
            "Medical diagnostic imaging center",
            "Medical laboratory",
            "Metal fabricator",
            "Metal machinery supplier",
            "Mountain peak",
            "Nail salon",
            "Performing arts theater",
            "Photography studio",
            "Playground",
            "Poultry farm",
            "Private hospital",
            "Private university",
            "Real estate agency",
            "Real estate consultant",
            "Real estate rental agency",
            "School",
            "Sculpture",
            "Subway station",
            "Senior high school",
            "Sento",
            "Sightseeing tour agency",
            "Software company",
            "Textile mill",
            "Tour agency",
            "Tourist information center",
            "Tradesmen",
            "Training centre",
            "Transportation service",
            "Travel Agents",
            "Used car dealer",
            "Vehicle exporter",
            "Wholesale plant nursery",
            "Wholesaler",
            "Train station",
            "Airports",
            "airport",
            "Sightseeing tour agency",
            "Laundromat",
            "Historical landmark",
            "Island",
            "Electronics manufacturer",
            "Corporate office",
            "Theme park",
            "Subway station",
            "Food manufacturer",
            "Art museum",
            "International airport",
            "Airport",
            "Garden",
            "Cinema",
            "Manufacturer",
            "Observation deck",
            "Mountain peak",
            "Amusement park",
            "Bridge",
            "Soy sauce maker",
            "Housing development",
            "Massage spa",
            "Waterfall",
            "Delivery service",
            "Water treatment supplier",
            "River",
            "Event venue",
            "Museum",
            "Florist",
            "Park",
            "Tourist attraction",
            "Business park",
            "Hair salon",
            "Holiday apartment",
            "Car racing track",
            "Language school",
            "Host club",
            "Shinto shrine",
            "Cultural center",
            "Foreign consulate",
            "Non-profit organization",
            "Truck parts supplier",
            "Gift shop",
            "Lake",
            "Spa",
            "Festival",
            "Beach",
            "Dog trainer",
            "Concert hall",
            "Tour operator",
            "Art gallery",
            "Health and beauty sho",
            "public bath",
            "review",
            "City park",
            "Community center",
            "Cooking class",
            "Coworking space",
            "Garment exporter",
            "General hospital",
            "Medical clinic",
            "Modern art museum",
            "Mobile caterer",
            "Scenic spot",
            "public bath",
            "Yoga studio",
            "Book publisher",
            "Caterer",
            "Photographer",
            "Student housing center",
            "Fortress",
            "Ryokan style hotels",
            "Sake breweries",
            "Kanda Shopping Street",
            "Onigiri Banshun Team",
            "At home with Nahoko",
            "L’obelisque",
            "Nakatsugawa Restaurant",
            "Cafedeartiste bakery",
            "Matcha Senkyu",
            "@kikkomanuk",
            "@Tesco",
            "Kono Mini",
            "Disney Tokyo, Japan",
            "7/11s,",
            "Miss 7",
            "Meat place",
            "fluffy pancake place",
            "#WadanoForestApartments",
            "Root2lab",
            "Monte Stella",
            "Cups (in Kamakura)",
            "Owara Tamaten",
            "Pop corn",
            "Amai Delights",
            "Oh! Teppanyaki Restaurant",
            "Ben Zai Ten",
            "Tokyo Midtown supermarket",
            "pink paper bakery",
            "Tokyo - Matsuya",
            "Flour fair",
            "Isepan bread event",
            "-",
            ////////////////////////////////////////////////
"Accountant",
"Acupuncturist",
"Addiction treatment center",
"Advertising agency",
"Agricultural association",
"Aluminum window",
"Animal protection organization",
"Animal rescue service",
"Archaeological site",
"Archipelago",
"Architect",
"Artist",
"Astrologer",
"ATV rental service",
"Auction house",
"Bathroom remodeler",
"Building consultant",
"Building materials supplier",
"Bus stop",
"Business development service",
"Business management consultant",
"Camping Ground",
"Canal",
"Car leasing service",
"Car rental agency",
"Car repair and maintenance service",
"Car wash",
"Castle",
"Cathedral",
"Child Care Centre",
"Civic center",
"Civil engineer",
"Cleaners",
"Cleaning products supplier",
"Cleaning service",
"Commercial printer",
"Computer consultant",
"Computer support and services",
"Concrete contractor",
"Condiments supplier",
"Consultant",
"Contractor",
"Cosmetics industry",
"Cottage rental",
"Council",
"Courier service",
"Crane service",
"Cruise terminal",
"Cultural association",
"Dairy farm",
"Dairy Products Supplier",
"Design agency",
"Diabetes Centre",
"Disability services and support organization",
"Distribution service",
"Dressmaker",
"Dynamometer supplier",
"E commerce agency",
"Energy supplier",
"Engineer",
"Engineering consultant",
"Engraver",
"Entertainment agency",
"Environment renewable natural resources",
"Event planner",
"Excavating contractor",
"Factory equipment supplier",
"Farm equipment supplier",
"Fax service",
"Ferry service",
"Finance broker",
"Financial consultant",
"Financial institution",
"Financial planner",
"Flour mill",
"Flower designer",
"Food manufacturing supply",
"Food producer",
"Food products supplier",
"Glacier",
"Gondola lift station",
"Grain elevator",
"Hair transplantation clinic",
"Handicraft",
//"Harbor",
"Hiking area",
"Hindu priest",
"Historical place",
"Housing society",
//"Hunting area",
"Hygiene Service",
//"Ice",
"Immigration attorney",
"Indoor lodging",
"Industrial equipment supplier",
"Interior architect office",
"Interior Decorator",
"Interior designer",
"Jeweler",
"Konditorei",
"Laboratory",
"Land mass",
"Laundry service",
"Law firm",
"Lawyers association",
"Leather goods supplier",
"Library",
"Lido",
"Life coach",
"Limousine service",
"Logistics service",
"Lottery retailer",
"Mailing service",
"Make-up artist",
"Medical Center",
"Military residence",
"Mobility equipment supplier",
"Monument",
"Mortgage broker",
"Mosque",
"Mountain cable car",
"Natural feature",
"Natural stone supplier",
"Nature preserve",
//"Non-governmental organization",
"Nutritionist",
"Occupational Rehabilitation Centre",
"Occupational therapist",
"Office",
"Office equipment rental service",
"Office refurbishment service",
"Ophthalmology clinic",
"Outdoor activity organiser",
"Painter",
"Party equipment rental service",
"Party planner",
"Peninsula",
"Permanent make-up clinic",
"Pharmacy",
"Photo agency",
"Pilates studio",
"Plant and machinery hire",
//"Plant nursery",
"Pond",
"Pond contractor",
"Precision engineer",
"Private educational institution",
"Promenade",
"Promotional products supplier",
"Psychic",
//"Public university",
"Publisher",
"Railway services",
"Real estate agent",
"Real estate developer",
"Recreation center",
"Recruiter",
"Recruitment Agency",
"Refrigerated transport service",
//"Religious destination",
//"Religious institution",
"Renovation contractor",
"Repair service",
"Research and product development",
"Research institute",
//"Residential college",
"Retreat center",
"Rock",
"Rocky",
"Safety equipment supplier",
//"Sauna",
"SCUBA instructor",
"Security guard service",
"Security service",
//"Self-catering accommodation",
//"Serviced accommodation",
//"Serviced apartment",
"Shipping and mailing service",
"Shipping service",
"Short term apartment rental agency",
"Signwriters",
"Solicitor",
//"Stadium",
"Storage facility",
"Surf lifesaving club",
"Swimming basin",
//"Swimming pool",
"Tailor",
"Tax preparation",
"Telecommunications service provider",
"Television station",
"Temp agency",
//"Tennis club",
"Thermal baths",
"Tiffin center",
"Townhouse complex",
"Training provider",
//"Tram stop",
//"Transit station",
"Translation service",
//"Transport hub",
//"University",
//"Vacation home rental agency",
//"Video arcade",
"Video production service",
"Villa",
"Visitor center",
"Volcano",
"Volunteer organization",
"Warehouse",
//"Water",
"Water works equipment supplier",
//"Wedding venue",
//"Wellness center",
//"Wellness program",
//"Wildlife Sanctuary",
"Window supplier",
"Women\"s health clinic",
"Wood working class",
"Woods",
"Yoga retreat center",
"Youth hostel",
//"Zoo",

            ];

        public static bool IsStore(string name)
        {
            List<string> storeNames = [
            "Food products supplier",
            "Condiments supplier",
            "Market",
            "Grocery store",
            "Catering food and drink supplier"
            ];
            if (name.Contains("Condiments supplier", StringComparison.InvariantCultureIgnoreCase)) return true;
            //Landmark
            //Food court?
            //Water park
            //Golf driving range
            //Ski resort
            //Dry cleaner
            return false;
        }

        /// <summary>
        /// Checks to see if the restaurant type is in the rejection list
        /// </summary>
        public bool IsRejectedRestaurantType(string? restaurantType)
        {

            if (string.IsNullOrWhiteSpace(restaurantType)) return false;
            return _rejectionList.Exists(o => o == restaurantType);
        }

        /// <summary>
        /// Gets a list of extracted restaurant types
        /// </summary>
        public List<string> GetRestaurantTypes()
        {
            _restaurantTypes.Sort();
            var data = new List<string>();
            var ignoreList = _rejectionList;
            foreach (var item in _restaurantTypes)
            {
                if (!item.Contains("shop", StringComparison.InvariantCultureIgnoreCase)
                    && !item.Contains("store", StringComparison.InvariantCultureIgnoreCase)
                    && !item.Contains("market", StringComparison.InvariantCultureIgnoreCase)
                    && !item.Contains("hotel", StringComparison.InvariantCultureIgnoreCase)
                    && !ignoreList.Any(s => item.Contains(s, StringComparison.InvariantCultureIgnoreCase))
                    )
                {
                    data.Add(item);
                }
            }
            return data;
        }

        /// <summary>
        /// Add a restaurant type to the data
        /// </summary>
        public void AddRestaurantType(string? restaurant)
        {
            if (!string.IsNullOrWhiteSpace(restaurant)
                && !_restaurantTypes.Contains(restaurant)
                && !_rejectionList.Contains(restaurant))
            {
                _restaurantTypes.Add(restaurant);
            }
        }

        /// <summary>
        /// clears the restaurant type data
        /// </summary>
        public void ClearRestaurantType()
        {
            _restaurantTypes.Clear();
        }
    }
}
