using OpenQA.Selenium.BiDi.Modules.Script;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.Intrinsics.Arm;
using System.Text;
using System.Threading.Tasks;

namespace Gluten.Core.LocationProcessing.Service
{
    public class RestaurantTypeService
    {

        public bool IsRejectedRestaurantType(string? restaurantType)
        {
            List<string> _rejectionList = [
            "Adult education school",
            "Aged Care Service",
            "Agricultural service",
            "Airline",
            "Animal hospital",
            "Arts organization",
            "Auditor",
            "Auto body parts supplier",
            "Bail bonds service",
            "Baseball field",
            "Beauty product supplier",
            "Beauty salon",
            "Biotechnology company",
            "Boat tour agency",
            //"Buddhist temple",
            "Bridge",
            "Business center",
            "Car dealer",
            "Cars",
            "Car racing track",
            "Charity",
            "Children's book store",
            "Clothes market",
            "Company",
            "Condominium complex",
            "Conference center",
            "Corporate office",
            "Cooking school",
            "Criminal justice attorney",
            "Cruise line company",
            //"Dairy farm",
            "Diagnostic center",
            "Driveshaft shop",
            "E-commerce service",
            "Education center",
            "Electronics manufacturer",
            "Embassy",
            "Energy equipment and solutions",
            "Executive search firm",
            "Exhibit",
            "Exporter",
            "Fashion designer",
            "Florist",
            "Fitness center",
            "Freight forwarding service",
            "Food manufacturer",
            "Furniture accessories",
            "Furniture maker",
            "Garden",
            "Glazier",
            "Golf course",
            //"Grain elevator",
            "Graphic designer",
            "Gym",
            "Hairdresser",
            "Handyman/Handywoman/Handyperson",
            "Health consultant",
            "Heritage building",
            "Hindu temple",
            //"Holiday home",
            //"Homestay",
            "Hair salon",
            "Historical landmark",
            "House cleaning service",
            "Housing complex",
            "Island",
            "Karaoke Equipment Hire Service",
            "Laundromat",
            "Language school",
            "Lawn bowls club",
            "Lawn care service",
            "Manufacturer",
            "Marriage or relationship counselor",
            "Masonic Centre",
            "Massage therapist",
            "Media house",
            "Medical diagnostic imaging center",
            "Medical laboratory",
            "Metal fabricator",
            "Metal machinery supplier",
            "Mountain peak",
            "Nail salon",
            "Performing arts theater",
            "Photography studio",
            "Playground",
            "Poultry farm",
            "Private hospital",
            "Private university",
            "Real estate agency",
            "Real estate consultant",
            "Real estate rental agency",
            "School",
            "Sculpture",
            "Subway station",
            "Senior high school",
            "Sento",
            "Sightseeing tour agency",
            "Software company",
            "Textile mill",
            "Tour agency",
            "Tourist information center",
            "Tradesmen",
            "Training centre",
            "Transportation service",
            "Travel Agents",
            "Used car dealer",
            "Vehicle exporter",
            "Wholesale plant nursery",
            "Wholesaler",
            ];

            if (string.IsNullOrWhiteSpace(restaurantType)) return false;
            return _rejectionList.Exists(o => o == restaurantType);
        }
    }
}
