export var Others: Array<string> = ['Train station',
    'Airports',
    'Sightseeing tour agency',
    'Laundromat',
    'Historical landmark',
    'Island',
    'Electronics manufacturer',
    'Corporate office',
    'Theme park',
    'Subway station',
    'Food manufacturer',
    'Art museum',
    'International airport',
    'Airport',
    'Garden',
    'Cinema',
    'Manufacturer',
    'Observation deck',
    'Mountain peak',
    'Amusement park',
    'Bridge',
    'Soy sauce maker',
    'Housing development',
    'Massage spa',
    'Waterfall',
    'Delivery service',
    'Water treatment supplier',
    'River',
    'Event venue',
    'Museum',
    'Florist',
    'Park',
    'Tourist attraction',
    'Business park',
    'Hair salon',
    'Holiday apartment',
    'Car racing track',
    'Language school',
    'Host club',
    'Shinto shrine',
    'Cultural center',
    'Foreign consulate',
    'Non-profit organization',
    'Truck parts supplier',
    'Gift shop',
    'Lake',
    'Spa',
    'Festival',
    'Beach',
    'Dog trainer',
    'Concert hall',
    'Tour operator',
    'Art gallery',
    'Health and beauty shop'];


export var restaurantTypes: string[] = [
    'All',
    'American restaurant',
    'Art cafe',
    'Asian fusion restaurant',
    'Asian restaurant',
    'Australian restaurant',
    'Bakery',
    'Bar',
    'Bar &amp; grill',
    'Barbecue restaurant',
    'Belgian restaurant',
    'Bistro',
    'Brazilian restaurant',
    'Breakfast restaurant',
    'Brewery',
    'Brewpub',
    'British restaurant',
    'Brunch restaurant',
    'Buddhist temple',
    'Buffet restaurant',
    'Cafe',
    'Cafeteria',
    'Charcuterie',
    'Chicken restaurant',
    'Chinese restaurant',
    'Cocktail bar',
    'Coffee roasters',
    'Conveyor belt sushi restaurant',
    'Crab house',
    'Creative cuisine restaurant',
    'Creperie',
    'Deli',
    'Dessert restaurant',
    'Dim sum restaurant',
    'Dog cafe',
    'Dumpling restaurant',
    'Falafel restaurant',
    'Family restaurant',
    'Fast food restaurant',
    'Fine dining restaurant',
    'Fish &amp; chips restaurant',
    'Fish restaurant',
    'Food court',
    'French restaurant',
    'Fried chicken takeaway',
    'Fruit parlor',
    'Fusion restaurant',
    'Gluten-free restaurant',
    'Greek restaurant',
    'Gyudon restaurant',
    'Hamburger restaurant',
    'Hawaiian restaurant',
    'Hawker stall',
    'Health food restaurant',
    'Hot pot restaurant',
    'Hunan restaurant',
    'Indian restaurant',
    'Irish pub',
    'Italian restaurant',
    'Izakaya restaurant',
    'Japanese curry restaurant',
    'Japanese delicatessen',
    'Japanese restaurant',
    'Japanese steakhouse',
    'Japanese sweets restaurant',
    'Japanized western restaurant',
    'Kaiseki restaurant',
    'Konditorei',
    'Korean barbecue restaurant',
    'Korean restaurant',
    'Kushiyaki restaurant',
    'Kyoto style Japanese restaurant',
    'Lebensmittelhändler',
    'Macrobiotic restaurant',
    'Matchaa year ago',
    'Meat dish restaurant',
    'Mexican restaurant',
    'Modern izakaya restaurant',
    'Mutton barbecue restaurant',
    'Nepalese restaurant',
    'New American restaurant',
    'Obanzai restaurant',
    'Okonomiyaki restaurant',
    'Organic restaurant',
    'Oyster bar restaurant',
    'Pakistani restaurant',
    'Pancake restaurant',
    'Patisserie',
    'Persian restaurant',
    'Pizza restaurant',
    'Pizza takeaway',
    'Pub',
    'Ramen restaurant',
    'Restauracja japońska (okonomiyaki)',
    'Restaurant',
    'Rice restaurant',
    'Ristorante italiano',
    'Sake brewery',
    'Samgyetang restaurant',
    'Seafood donburi restaurant',
    'Seafood restaurant',
    'Shabu-shabu restaurant',
    'Sichuan restaurant',
    'Singaporean restaurant',
    'Snack bar',
    'South Indian restaurant',
    'Southeast Asian restaurant',
    'Sports bar',
    'Steak house',
    'Sukiyaki and Shabu Shabu restaurant',
    'Sushi restaurant',
    'Sushirestaurant med transportbånd',
    'Swiss restaurant',
    'Syokudo and Teishoku restaurant',
    'Taco restaurant',
    'Taiwanese restaurant',
    'Take Away Restaurant',
    'Tapas bar',
    'Tapas restaurant',
    'Tea house',
    'Tempura restaurant',
    'Teppanyaki restaurant',
    'Teppanyaki-Restaurant',
    'Tex-Mex restaurant',
    'Thai restaurant',
    'Tofu restaurant',
    'Tonkatsu restaurant',
    'Traditional restaurant',
    'Traditional teahouse',
    'Udon noodle restaurant',
    'Unagi restaurant',
    'Vegan restaurant',
    'Vegetarian cafe and deli',
    'Vegetarian restaurant',
    'Vietnamese restaurant',
    'Warehouse club',
    'West African restaurant',
    'Western restaurant',
    'Wholesale bakery',
    'Yakatabune',
    'Yakiniku restaurant',
    'Yakitori restaurant',
];