using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GlutenApp.Services
{
    class CardLookupService
    {
        private static Dictionary<string, string> _countryLanguages = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        {"AF", "Pashto/Dari"},
        {"AL", "Albanian"},
        {"DZ", "Arabic"},
        {"AS", "English/Samoan"},
        {"AD", "Catalan"},
        {"AO", "Portuguese"},
        {"AR", "Spanish"},
        {"AM", "Armenian"},
        {"AU", "English"},
        {"AT", "German"},
        {"AZ", "Azerbaijani"},
        {"BS", "English"},
        {"BH", "Arabic"},
        {"BD", "Bengali"},
        {"BB", "English"},
        {"BY", "Belarusian/Russian"},
        {"BE", "Dutch/French/German"},
        {"BZ", "English"},
        {"BJ", "French"},
        {"BT", "Dzongkha"},
        {"BO", "Spanish"},
        {"BA", "Bosnian/Croatian/Serbian"},
        {"BW", "English/Setswana"},
        {"BR", "Portuguese"},
        {"BN", "Malay"},
        {"BG", "Bulgarian"},
        {"BF", "French"},
        {"BI", "Kirundi/French/English"},
        {"KH", "Khmer"},
        {"CM", "French/English"},
        {"CA", "English/French"},
        {"CV", "Portuguese"},
        {"CF", "French/Sango"},
        {"TD", "French/Arabic"},
        {"CL", "Spanish"},
        {"CN", "Chinese"},
        {"CO", "Spanish"},
        {"KM", "Comorian/Arabic/French"},
        {"CD", "French"},
        {"CG", "French"},
        {"CR", "Spanish"},
        {"HR", "Croatian"},
        {"CU", "Spanish"},
        {"CY", "Greek/Turkish"},
        {"CZ", "Czech"},
        {"DK", "Danish"},
        {"DJ", "French/Arabic"},
        {"DM", "English"},
        {"DO", "Spanish"},
        {"EC", "Spanish"},
        {"EG", "Arabic"},
        {"SV", "Spanish"},
        {"GQ", "Spanish/French/Portuguese"},
        {"ER", "Tigrinya/Arabic/English"},
        {"EE", "Estonian"},
        {"ET", "Amharic"},
        {"FJ", "English/Fijian/Hindi"},
        {"FI", "Finnish/Swedish"},
        {"FR", "French"},
        {"GA", "French"},
        {"GM", "English"},
        {"GE", "Georgian"},
        {"DE", "German"},
        {"GH", "English"},
        {"GR", "Greek"},
        {"GD", "English"},
        {"GT", "Spanish"},
        {"GN", "French"},
        {"GW", "Portuguese"},
        {"GY", "English"},
        {"HT", "French/Haitian Creole"},
        {"HN", "Spanish"},
        {"HU", "Hungarian"},
        {"IS", "Icelandic"},
        {"IN", "Hindi/English"},
        {"ID", "Indonesian"},
        {"IR", "Persian"},
        {"IQ", "Arabic/Kurdish"},
        {"IE", "Irish/English"},
        {"IL", "Hebrew/Arabic"},
        {"IT", "Italian"},
        {"JM", "English"},
        {"JP", "Japanese"},
        {"JO", "Arabic"},
        {"KZ", "Kazakh/Russian"},
        {"KE", "English/Swahili"},
        {"KI", "English/Gilbertese"},
        {"KP", "Korean"},
        {"KR", "Korean"},
        {"KW", "Arabic"},
        {"KG", "Kyrgyz/Russian"},
        {"LA", "Lao"},
        {"LV", "Latvian"},
        {"LB", "Arabic"},
        {"LS", "English/Sesotho"},
        {"LR", "English"},
        {"LY", "Arabic"},
        {"LI", "German"},
        {"LT", "Lithuanian"},
        {"LU", "Luxembourgish/French/German"},
        {"MG", "Malagasy/French"},
        {"MW", "English/Chichewa"},
        {"MY", "Malay"},
        {"MV", "Dhivehi"},
        {"ML", "French"},
        {"MT", "Maltese/English"},
        {"MH", "Marshallese/English"},
        {"MR", "Arabic"},
        {"MU", "English/French"},
        {"MX", "Spanish"},
        {"FM", "English"},
        {"MD", "Romanian"},
        {"MC", "French"},
        {"MN", "Mongolian"},
        {"ME", "Montenegrin"},
        {"MA", "Arabic/Berber"},
        {"MZ", "Portuguese"},
        {"MM", "Burmese"},
        {"NA", "English"},
        {"NR", "Nauruan/English"},
        {"NP", "Nepali"},
        {"NL", "Dutch"},
        {"NZ", "English/Maori"},
        {"NI", "Spanish"},
        {"NE", "French"},
        {"NG", "English"},
        {"NO", "Norwegian"},
        {"OM", "Arabic"},
        {"PK", "Urdu/English"},
        {"PW", "Palauan/English"},
        {"PA", "Spanish"},
        {"PG", "English/Hiri Motu/Tok Pisin"},
        {"PY", "Spanish/Guarani"},
        {"PE", "Spanish"},
        {"PH", "Filipino/English"},
        {"PL", "Polish"},
        {"PT", "Portuguese"},
        {"QA", "Arabic"},
        {"RO", "Romanian"},
        {"RU", "Russian"},
        {"RW", "Kinyarwanda/French/English"},
        {"KN", "English"},
        {"LC", "English"},
        {"VC", "English"},
        {"WS", "Samoan/English"},
        {"SM", "Italian"},
        {"ST", "Portuguese"},
        {"SA", "Arabic"},
        {"SN", "French"},
        {"RS", "Serbian"},
        {"SC", "Seychellois Creole/English/French"},
        {"SL", "English"},
        {"SG", "English/Malay/Mandarin/Tamil"},
        {"SK", "Slovak"},
        {"SI", "Slovene"},
        {"SB", "English"},
        {"SO", "Somali/Arabic"},
        {"ZA", "Zulu/Xhosa/Afrikaans/English/Setswana/Sesotho"},
        {"SS", "English"},
        {"ES", "Spanish"},
        {"LK", "Sinhala/Tamil"},
        {"SD", "Arabic/English"},
        {"SR", "Dutch"},
        {"SE", "Swedish"},
        {"CH", "German/French/Italian/Romansh"},
        {"SY", "Arabic"},
        {"TW", "Mandarin"},
        {"TJ", "Tajik"},
        {"TZ", "Swahili/English"},
        {"TH", "Thai"},
        {"TL", "Tetum/Portuguese"},
        {"TG", "French"},
        {"TO", "Tongan/English"},
        {"TT", "English"},
        {"TN", "Arabic"},
        {"TR", "Turkish"},
        {"TM", "Turkmen"},
        {"TV", "Tuvaluan/English"},
        {"UG", "English/Swahili"},
        {"UA", "Ukrainian"},
        {"AE", "Arabic"},
        {"GB", "English"},
        {"US", "English"},
        {"UY", "Spanish"},
        {"UZ", "Uzbek"},
        {"VU", "Bislama/English/French"},
        {"VE", "Spanish"},
        {"VN", "Vietnamese"},
        {"YE", "Arabic"},
        {"ZM", "English"},
        {"ZW", "English/Shona/Sindebele"}
        // Add more country codes and their languages as needed
    };

        public static string GetLanguageByCountryCode(string countryCode)
        {
            if (_countryLanguages.TryGetValue(countryCode, out string language))
            {
                return language;
            }
            else
            {
                return "Language not found";
            }
        }

        public string GetCardPath(string countryCode)
        {
            var languages = GetLanguageByCountryCode(countryCode);
            if (languages.Contains("/"))
            {
                var language = languages.Split("/")[0];

                return $"{language}_gluten_free_restaurant_card.png";
            }

            return $"{languages}_gluten_free_restaurant_card.png";
        }
    }
}
